name: GateKeeper
main: is.gussi.bukkit.plugin.gatekeeper.GateKeeper
version: 0.1
website: http://github.com/gussi/GateKeeper
author: Gussi
description: Yet another whitelist plugin for bukkit
commands:
  whitelist:
    description: Whitelist management
    usage: /<command> [add/remove/check] [ip/cidr/player]
    aliases: [wl]
  blacklist:
    description: Blacklist management
    usage: /<command> [add/remove/check] [ip/cidr/player]
    aliases: [bl]
