name: GateKeeper
main: is.gussi.bukkit.plugin.gatekeeper.GateKeeper
version: 0.1.1
website: http://github.com/gussi/GateKeeper
author: Gussi
description: Yet another whitelist plugin for bukkit
commands:
  gatekeeper:
    description: GateKeeper management
    usage: /<command> help
    aliases: [gk, wl, bl, whitelist, blacklist]