name: Whitelist
main: is.gussi.bukkit.plugin.whitelist.Whitelist
version: 0.1
website: http://github.com/gussi/Whitelist
author: Gussi
description: Whitelist plugin for bukkit
commands:
  whitelist:
    description: Whitelist management
    usage: /<command> [add/remove/check] [ip/cidr/player]
    aliases: [wl]
  blacklist:
    description: Blacklist management
    usage: /<command> [add/remove/check] [ip/cidr/player]
    aliases: [bl]